/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package edu.ijse.mvc.view;

import edu.ijse.mvc.controller.CustomerController;
import edu.ijse.mvc.controller.ItemController;
import edu.ijse.mvc.dto.CustomerDto;
import edu.ijse.mvc.dto.ItemDto;
import edu.ijse.mvc.dto.OrderDetailDto;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author neths
 */
public class OrderView extends javax.swing.JFrame {

    ItemController itemController;
    CustomerController customerController;
    ArrayList<OrderDetailDto> orderDetailDtos;

    /**
     * Creates new form OrderView
     */
    public OrderView() {
        itemController = new ItemController();
        customerController = new CustomerController();
        orderDetailDtos = new ArrayList<>();
        initComponents();
        loadTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        ordertile = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lblOrderID = new javax.swing.JLabel();
        txtOrderID = new javax.swing.JTextField();
        txtCustID = new javax.swing.JTextField();
        lblCustId = new javax.swing.JLabel();
        txtItemID = new javax.swing.JTextField();
        lblItemId = new javax.swing.JLabel();
        custSearchbtn = new javax.swing.JButton();
        itemSearchbtn = new javax.swing.JButton();
        lblcustdetails = new javax.swing.JLabel();
        lblitemdetail = new javax.swing.JLabel();
        lblcustdetails1 = new javax.swing.JLabel();
        txtQty = new javax.swing.JTextField();
        lblqty = new javax.swing.JLabel();
        lblDiscount = new javax.swing.JLabel();
        addQtybtn = new javax.swing.JButton();
        txtDiscount = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblItem = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ordertile.setFont(new java.awt.Font("Arial Black", 0, 20)); // NOI18N
        ordertile.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ordertile.setText("Order");

        lblOrderID.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblOrderID.setText("Order ID");

        txtOrderID.setFont(new java.awt.Font("Eras Bold ITC", 0, 14)); // NOI18N

        txtCustID.setFont(new java.awt.Font("Eras Bold ITC", 0, 14)); // NOI18N

        lblCustId.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblCustId.setText("Cust ID");

        txtItemID.setFont(new java.awt.Font("Eras Bold ITC", 0, 14)); // NOI18N

        lblItemId.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblItemId.setText("Item ID");

        custSearchbtn.setText("Search");
        custSearchbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                custSearchbtnMouseClicked(evt);
            }
        });

        itemSearchbtn.setText("Search");
        itemSearchbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                itemSearchbtnMouseClicked(evt);
            }
        });
        itemSearchbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemSearchbtnActionPerformed(evt);
            }
        });

        lblcustdetails.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        lblcustdetails.setForeground(new java.awt.Color(255, 0, 0));

        lblitemdetail.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        lblitemdetail.setForeground(new java.awt.Color(255, 0, 0));

        lblcustdetails1.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        lblcustdetails1.setForeground(new java.awt.Color(255, 0, 0));

        txtQty.setFont(new java.awt.Font("Eras Bold ITC", 0, 14)); // NOI18N

        lblqty.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblqty.setText("QTY");

        lblDiscount.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblDiscount.setText("Discount");

        addQtybtn.setText("ADD");
        addQtybtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addQtybtnMouseClicked(evt);
            }
        });
        addQtybtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addQtybtnActionPerformed(evt);
            }
        });

        txtDiscount.setFont(new java.awt.Font("Eras Bold ITC", 0, 14)); // NOI18N

        tblItem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tblItem);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(ordertile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 722, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblOrderID)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtOrderID, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(lblItemId, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(lblCustId, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtCustID, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtItemID, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(lblqty, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtQty, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(custSearchbtn)
                                        .addGap(18, 18, 18)
                                        .addComponent(lblcustdetails, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(lblDiscount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(itemSearchbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblitemdetail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(txtDiscount, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(addQtybtn)
                                                .addGap(228, 228, 228)))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblcustdetails1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ordertile, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblOrderID)
                    .addComponent(txtOrderID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblcustdetails, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblCustId)
                        .addComponent(txtCustID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(custSearchbtn)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblItemId)
                        .addComponent(txtItemID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(itemSearchbtn))
                    .addComponent(lblitemdetail, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblcustdetails1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblqty)
                    .addComponent(txtQty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDiscount)
                    .addComponent(addQtybtn)
                    .addComponent(txtDiscount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemSearchbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemSearchbtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemSearchbtnActionPerformed

    private void itemSearchbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_itemSearchbtnMouseClicked
        searchItem();
    }//GEN-LAST:event_itemSearchbtnMouseClicked

    private void custSearchbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_custSearchbtnMouseClicked
        searchCustomer();
    }//GEN-LAST:event_custSearchbtnMouseClicked

    private void addQtybtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addQtybtnMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_addQtybtnMouseClicked

    private void addQtybtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addQtybtnActionPerformed
        addToTable();
    }//GEN-LAST:event_addQtybtnActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(OrderView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(OrderView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(OrderView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(OrderView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new OrderView().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addQtybtn;
    private javax.swing.JButton custSearchbtn;
    private javax.swing.JButton itemSearchbtn;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel lblCustId;
    private javax.swing.JLabel lblDiscount;
    private javax.swing.JLabel lblItemId;
    private javax.swing.JLabel lblOrderID;
    private javax.swing.JLabel lblcustdetails;
    private javax.swing.JLabel lblcustdetails1;
    private javax.swing.JLabel lblitemdetail;
    private javax.swing.JLabel lblqty;
    private javax.swing.JLabel ordertile;
    private javax.swing.JTable tblItem;
    private javax.swing.JTextField txtCustID;
    private javax.swing.JTextField txtDiscount;
    private javax.swing.JTextField txtItemID;
    private javax.swing.JTextField txtOrderID;
    private javax.swing.JTextField txtQty;
    // End of variables declaration//GEN-END:variables

    private void searchItem() {
        try {
            String itemId = txtItemID.getText();

            ItemDto itemDto = itemController.searchItem(itemId);
            if (itemDto != null) {
                lblitemdetail.setText(itemDto.getDescription() + "    " + itemDto.getPacksize() + "     Rs." + itemDto.getUnitprice());

            } else {
                JOptionPane.showMessageDialog(this, "Item not Found");

            }
        } catch (Exception ex) {
            Logger.getLogger(OrderView.class.getName()).log(Level.SEVERE, null, ex);
            System.out.println("Not working search Item");
        }
    }

    private void searchCustomer() {
        try {
            String custId = txtCustID.getText();
            CustomerDto dto;

            dto = customerController.searchCustomer(Integer.parseInt(custId));
            if (dto != null) {
                lblcustdetails.setText(dto.getTitle() + " " + dto.getName() + "         " + dto.getCity());

            } else {
                JOptionPane.showMessageDialog(this, "Customer not Found");

            }

        } catch (Exception ex) {
            Logger.getLogger(OrderView.class.getName()).log(Level.SEVERE, null, ex);
            System.out.println("Not working search Customer");

        }

    }

    private void loadTable() {
        String[] columns = {"ItemCode", "Qty", "Discount"};
        DefaultTableModel dtm = new DefaultTableModel(columns, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
            
        };
        tblItem.setModel(dtm);
        
        
    }

    private void clear(){
        txtCustID.setText("");
        txtItemID.setText("");
        txtOrderID.setText("");
        txtQty.setText("");
        txtDiscount.setText("");
    }
    private void addToTable() {
        OrderDetailDto orderDetailDto = new OrderDetailDto();
        orderDetailDto.setItemCode(txtItemID.getText());
        orderDetailDto.setOrderQty(Integer.parseInt(txtQty.getText()));
        orderDetailDto.setDiscount(Double.parseDouble(txtDiscount.getText()));
        
        orderDetailDtos.add(orderDetailDto);
        
        Object [] rowData = {orderDetailDto.getItemCode(),orderDetailDto.getOrderQty(),orderDetailDto.getDiscount()};
        DefaultTableModel dtm = (DefaultTableModel)tblItem.getModel();
        dtm.addRow(rowData);
        
        clear();
        
    }
}
